name: Q&A

on:
    pull_request_target:

defaults:
    run:
        shell: bash

jobs:
    call-qa:
        uses: symfony-php-recipes/symfony-recipes-php/.github/workflows/callable-qa.yml@main
        secrets:
            token: ${{ secrets.BOT_TOKEN }}
